### ISSUE TITLE
null function or function signature mismatch

### ISSUE THREAD

**Issue by shikoshib** [FigmentBoy/GDWeb#3]
Hello. Really nice project, but I can't view a level (id: 95540029) because of the error mentioned in the title.
![image](https://github.com/FigmentBoy/GDWeb/assets/100675079/1460026e-95a2-45ef-8542-81f0b8c3eba8)
I hope you'd look into this.

**Comment by FigmentBoy** [comment]
Hey, this should've been fixed with a recent commit. Thank you for reporting!
