### ISSUE TITLE
where are the coins?

### ISSUE THREAD

**Issue by polygoners1** [FigmentBoy/GDWeb#4]
like where are they? here is the PNG you can use : 
![silvercoin](https://github.com/FigmentBoy/GDWeb/assets/149721398/1a031f57-673e-437d-849f-168de443fcbf)

**Comment by FigmentBoy** [comment]
Thank you for your issue! I'm planning to pack the remaining missing textures (including coins, most animated objects, and text) into a single spritesheet so that they can be used in-game. While I appreciate the sentiment, I don't think just using a singular png for coins is an efficient use of sprite slots.

**Comment by polygoners1** [comment]
also, what about the gaps in the green and black orbs? (use dark mode to see)
![green](https://github.com/FigmentBoy/GDWeb/assets/149721398/72cc341a-e661-47d9-ba7d-6695a76e60cf)
![black](https://github.com/FigmentBoy/GDWeb/assets/149721398/67eb5c66-6ca6-4ad8-abd5-d7835565da4a)

**Comment by FigmentBoy** [comment]
I directly use the game's textures. Anything that appears in the `GJGameSheet` files is how it appears in GDWeb.

**Comment by polygoners1** [comment]
> I directly use the game's textures. Anything that appears in the `GJGameSheet` files is how it appears in GDWeb.

ohhhh, so since the gamesheet bg color is the same as the ring around the orbs, it blends into the orb?

**Comment by polygoners1** [comment]
> > I directly use the game's textures. Anything that appears in the `GJGameSheet` files is how it appears in GDWeb.
> 
> ohhhh, so since the gamesheet bg color is the same as the ring around the orbs, it blends into the orb?

hello?

**Comment by FigmentBoy** [comment]
The gamesheets have transparent backgrounds. The ring in game is an effect and is not programmed into GDWeb yet.

**Comment by polygoners1** [comment]
> The gamesheets have transparent backgrounds. The ring in game is an effect and is not programmed into GDWeb yet.

ok!
